import 'package:flutter/material.dart';

/// Global notifier for the current language ('en', 'hi', 'mr')
final ValueNotifier<String> localeNotifier = ValueNotifier<String>('en');

class T {
  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'welcome_back': 'Welcome back,',
      'find_course': 'Find a course you want to learn',
      'categories': 'Categories',
      'featured_courses': 'Featured Courses',
      'search': 'Search',
      'home': 'Explore',
      'my_courses': 'Academy',
      'chat': 'Chat',
      'search': 'Search',
      'feed': 'Community',
      'profile': 'Account',
      'edit_profile': 'Edit Profile',
      'language': 'Language',
      'notifications': 'Notifications',
      'help_support': 'Help & Support',
      'about': 'About',
      'logout': 'Logout',
      'courses': 'Courses',
      'completed': 'Completed',
      'certificates': 'Certificates',
      'welcome_header': 'Welcome To Bharatam Learning Platform',
      'my_learning': 'My Learning',
      'view_all': 'View All',
      'top_instructors': 'Top Instructors',
      'see_all': 'See All',
      'no_courses_in': 'No Courses in',
      'explore_other_category': 'Try exploring another category or check back later.',
      'progress_courses': 'Progress Courses',
      'completed_courses': 'Completed Courses',
      'support_chat': 'Support Chat',
      'courses_suffix': 'Courses',
      'no_completed_courses': 'No Completed Courses',
      'no_courses_in_progress': 'No Courses In Progress',
      'complete_lectures_to_earn': 'Complete all lectures in a course to earn your verified certificate!',
      'explore_catalog_to_start': 'Explore our catalog and purchase a course to start learning.',
      'view_certificate': 'View Certificate',
      'continue_learning': 'Continue Learning',
      'about_app_title': 'About the App',
      'about_app_desc': 'Bharatam LMS is a premium learning management system dedicated to preserving and sharing India\'s classical knowledge. From Vedic Mathematics to Sanskrit, Yoga to Indian History — learn from expert trainers with structured courses, interactive modules, and verified certifications.\n\nOur mission is to make traditional Indian education accessible to learners across the globe through modern technology.',
      'how_to_use': 'How to Use',
      'browse_courses_step': 'Browse Courses',
      'browse_courses_desc': 'Explore our catalog of courses on the home screen',
      'purchase_content_step': 'Purchase Content',
      'purchase_content_desc': 'Buy full courses, individual modules, or single videos',
      'watch_learn_step': 'Watch & Learn',
      'watch_learn_desc': 'Stream videos anytime, track your progress',
      'earn_certificate_step': 'Earn Certificate',
      'earn_certificate_desc': 'Complete all videos to get a verified certificate',
      'key_features': 'Key Features',
      'hd_video': 'HD Video Streaming',
      'verified_certs': 'Verified Certificates',
      'multi_lang': 'Multi-language Support',
      'secure_content': 'Secure Content Protection',
      'dark_mode': 'Dark Mode',
      'made_with_love': 'Made with ❤️ in India',
      'copyright': '© 2026 Bharatam LMS. All rights reserved.',
      'how_can_we_help': 'How can we help?',
      'here_to_assist': 'We\'re here to assist you with anything',
      'faqs': 'Frequently Asked Questions',
      'contact_us': 'Contact Us',
      'email_support': 'Email Support',
      'call_us': 'Call Us',
      'whatsapp': 'WhatsApp',
      'faq_q1': 'How do I purchase a course?',
      'faq_a1': 'Go to the course detail page and tap on the price button. You can buy the full course, individual modules, or single videos.',
      'faq_q2': 'Can I get a refund?',
      'faq_a2': 'Yes! We offer a 30-day refund policy for all purchases. Contact support to initiate a refund.',
      'faq_q3': 'How do I download my certificate?',
      'faq_a3': 'Once you complete all videos in a course, go to My Courses → Completed → View Certificate → Download.',
      'faq_q4': 'How do I change the app language?',
      'faq_a4': 'Go to Profile → Language and select your preferred language (English, Hindi, or Marathi).',
      'logout_confirm_title': 'Logout?',
      'logout_confirm_msg': 'Are you sure you want to logout? You\'ll need to login again to access your courses.',
      'cancel': 'Cancel',
      // Edit Profile
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'email_optional': 'Email (Optional)',
      'save_changes': 'Save Changes',
      'profile_updated': 'Profile updated successfully!',
      // Notifications
      'stay_updated': 'Stay Updated',
      'manage_notif_pref': 'Manage your notification preferences',
      'push_notifications': 'Push Notifications',
      'course_updates': 'Course Updates',
      'get_notif_enrolled_courses': 'Get notified about enrolled courses',
      'new_videos': 'New Videos',
      'new_videos_desc': 'When trainers upload new content',
      'study_reminders': 'Study Reminders',
      'study_reminders_desc': 'Daily learning reminders',
      'promotions_offers': 'Promotions & Offers',
      'promotions_offers_desc': 'Discounts and special offers',
      // Chat
      'access_denied': 'Access Denied',
      'please_login_chat': 'Please log in to chat with support.',
      'bharatam_support_chat': 'Bharatam Support Chat',
      'ask_anything_online': 'Ask us anything • Online',
      'start_conversation': 'Start a Conversation',
      'chat_intro_desc': 'Ask us about course details, technical issues, payments, or certificates. Our support team is here to guide you!',
      'support_admin': 'Support Admin',
      'type_message_hint': 'Type your message...',
      // Search
      'search_placeholder': 'Search courses, instructors...',
      'type_to_search': 'Type above to start searching...',
      'recent_searches': 'Recent Searches',
      'clear_all': 'Clear All',
      'no_courses_found': 'No Courses Found',
      'no_courses_found_desc': 'Try adjusting your search keywords or applying a different filter.',
      'filter_all': 'All',
      'filter_free': 'Free',
      'filter_paid': 'Paid',
      'filter_hindi': 'Hindi',
      'filter_english': 'English',
      'filter_sanskrit': 'Sanskrit',
      // Course Detail
      'tab_videos': 'Videos',
      'tab_pdfs': 'PDFs',
      'empty_videos': 'No video lectures available for this course.',
      'empty_pdfs': 'No PDF materials available for this course.',
      'from_price': 'From',
      'view_plans': 'View Plans',
      'downloaded_success': 'Downloaded "{title}" successfully!',
      'videos_count_label': '{count} videos',
      'modules_count_label': '{count} modules',
      // Video Player
      'rating_enabled': 'Rating enabled',
      'complete_to_rate': 'Complete to rate',
      'no_ratings_yet': 'No ratings yet',
      'your_rating_prefix': 'Your rating: {rating}',
      'give_rating': 'Give Rating',
      'update_rating': 'Update Rating',
      'mark_complete': 'Mark Complete',
      'certificate': 'Certificate',
      'rate_this_lecture': 'Rate this lecture',
      'submit_rating': 'Submit Rating',
      'rating_saved_msg': 'Thanks. Your lecture rating is saved.',
      'initializing_player': 'Initializing player...',
      'loading_video': 'Loading video...',
      'pdf_learning_resource': 'PDF learning resource',
      'audio_only': 'Audio only',
      // My Certificates
      'my_certificates': 'My Certificates',
      'no_certs_earned_yet': 'No Certificates Earned Yet',
      'no_certs_earned_desc': 'Complete 100% of the lectures in any of your purchased courses to unlock your verified, downloadable certificate!',
      'verified_certificate': 'Verified Certificate',
      'instructor_prefix': 'Instructor: {name}',
      'earned_on': 'Earned On',
      'view_download': 'View & Download',
    },
    'hi': {
      'welcome_back': 'वापसी पर स्वागत है,',
      'find_course': 'वह कोर्स खोजें जो आप सीखना चाहते हैं',
      'categories': 'श्रेणियाँ',
      'featured_courses': 'विशेष पाठ्यक्रम',
      'search': 'खोजें',
      'home': 'एक्सप्लोर',
      'my_courses': 'अकादमी',
      'chat': 'चैट',
      'feed': 'कम्युनिटी',
      'profile': 'अकाउंट',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'language': 'भाषा (Language)',
      'notifications': 'सूचनाएं',
      'help_support': 'मदद और समर्थन',
      'about': 'हमारे बारे में',
      'logout': 'लॉग आउट',
      'courses': 'पाठ्यक्रम',
      'completed': 'पूरा किया',
      'certificates': 'प्रमाणपत्र',
      'welcome_header': 'भारतम् लर्निंग प्लेटफॉर्म में आपका स्वागत है',
      'my_learning': 'मेरी सीख',
      'view_all': 'सभी देखें',
      'top_instructors': 'शीर्ष शिक्षक',
      'see_all': 'सभी देखें',
      'no_courses_in': 'इसमें कोई कोर्स नहीं है:',
      'explore_other_category': 'कृपया अन्य श्रेणी खोजें या बाद में देखें।',
      'progress_courses': 'प्रगतिशील पाठ्यक्रम',
      'completed_courses': 'पूर्ण पाठ्यक्रम',
      'support_chat': 'सहायता चैट',
      'courses_suffix': 'पाठ्यक्रम',
      'no_completed_courses': 'कोई पूर्ण पाठ्यक्रम नहीं',
      'no_courses_in_progress': 'कोई प्रगतिशील पाठ्यक्रम नहीं',
      'complete_lectures_to_earn': 'सत्यापित प्रमाणपत्र प्राप्त करने के लिए कोर्स के सभी व्याख्यान पूरे करें!',
      'explore_catalog_to_start': 'सीखना शुरू करने के लिए हमारे कैटलॉग को देखें और कोर्स खरीदें।',
      'view_certificate': 'प्रमाणपत्र देखें',
      'continue_learning': 'सीखना जारी रखें',
      'about_app_title': 'ऐप के बारे में',
      'about_app_desc': 'भारतम् एलएमएस एक प्रीमियम लर्निंग मैनेजमेंट सिस्टम है जो भारत के शास्त्रीय ज्ञान को संरक्षित करने और साझा करने के लिए समर्पित है। वैदिक गणित से लेकर संस्कृत, योग से लेकर भारतीय इतिहास तक - संरचित पाठ्यक्रमों, इंटरैक्टिव मॉड्यूल और सत्यापित प्रमाणपत्रों के साथ विशेषज्ञ प्रशिक्षकों से सीखें।\n\nहमारा मिशन आधुनिक तकनीक के माध्यम से दुनिया भर के शिक्षार्थियों के लिए पारंपरिक भारतीय शिक्षा को सुलभ बनाना है।',
      'how_to_use': 'उपयोग कैसे करें',
      'browse_courses_step': 'पाठ्यक्रम ब्राउज़ करें',
      'browse_courses_desc': 'होम स्क्रीन पर हमारे पाठ्यक्रमों की सूची देखें',
      'purchase_content_step': 'सामग्री खरीदें',
      'purchase_content_desc': 'पूरे पाठ्यक्रम, व्यक्तिगत मॉड्यूल या एकल वीडियो खरीदें',
      'watch_learn_step': 'देखें और सीखें',
      'watch_learn_desc': 'किसी भी समय वीडियो स्ट्रीम करें, अपनी प्रगति को ट्रैक करें',
      'earn_certificate_step': 'प्रमाणपत्र प्राप्त करें',
      'earn_certificate_desc': 'सत्यापित प्रमाणपत्र प्राप्त करने के लिए सभी वीडियो पूरे करें',
      'key_features': 'प्रमुख विशेषताएं',
      'hd_video': 'एचडी वीडियो स्ट्रीमिंग',
      'verified_certs': 'सत्यापित प्रमाणपत्र',
      'multi_lang': 'बहुभाषी समर्थन',
      'secure_content': 'सुरक्षित सामग्री सुरक्षा',
      'dark_mode': 'डार्क मोड',
      'made_with_love': 'भारत में ❤️ के साथ बनाया गया',
      'copyright': '© 2026 भारतम् एलएमएस। सर्वाधिकार सुरक्षित।',
      'how_can_we_help': 'हम आपकी क्या सहायता कर सकते हैं?',
      'here_to_assist': 'हम आपकी किसी भी चीज़ में सहायता के लिए यहाँ हैं',
      'faqs': 'अक्सर पूछे जाने वाले प्रश्न',
      'contact_us': 'संपर्क करें',
      'email_support': 'ईमेल सहायता',
      'call_us': 'हमें कॉल करें',
      'whatsapp': 'व्हाट्सएप',
      'faq_q1': 'मैं कोर्स कैसे खरीदूं?',
      'faq_a1': 'कोर्स विवरण पृष्ठ पर जाएं और मूल्य बटन पर टैप करें। आप पूरा कोर्स, व्यक्तिगत मॉड्यूल या एकल वीडियो खरीद सकते हैं।',
      'faq_q2': 'क्या मुझे रिफंड मिल सकता है?',
      'faq_a2': 'हाँ! हम सभी खरीदारियों के लिए 30 दिनों की धनवापसी नीति प्रदान करते हैं। धनवापसी शुरू करने के लिए सहायता से संपर्क करें।',
      'faq_q3': 'मैं अपना प्रमाणपत्र कैसे डाउनलोड करूं?',
      'faq_a3': 'एक बार जब आप एक कोर्स में सभी वीडियो पूरे कर लेते हैं, तो मेरे पाठ्यक्रम → पूर्ण → प्रमाणपत्र देखें → डाउनलोड पर जाएं।',
      'faq_q4': 'मैं ऐप की भाषा कैसे बदलूं?',
      'faq_a4': 'गोते प्रोफ़ाइल → भाषा पर जाएँ और अपनी पसंदीदा भाषा (अंग्रेजी, हिंदी या मराठी) चुनें।',
      'logout_confirm_title': 'लॉग आउट करें?',
      'logout_confirm_msg': 'क्या आप लॉग आउट करना चाहते हैं? अपने पाठ्यक्रमों तक पहुँचने के लिए आपको फिर से लॉग इन करना होगा।',
      'cancel': 'रद्द करें',
      // Edit Profile
      'full_name': 'पूरा नाम',
      'phone_number': 'फ़ोन नंबर',
      'email_optional': 'ईमेल (वैकल्पिक)',
      'save_changes': 'बदलाव सहेजें',
      'profile_updated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
      // Notifications
      'stay_updated': 'अपडेट रहें',
      'manage_notif_pref': 'अपनी सूचना प्राथमिकताएं प्रबंधित करें',
      'push_notifications': 'पुश सूचनाएं',
      'course_updates': 'पाठ्यक्रम अपडेट',
      'get_notif_enrolled_courses': 'नामांकित पाठ्यक्रमों के बारे में सूचित रहें',
      'new_videos': 'नए वीडियो',
      'new_videos_desc': 'जब शिक्षक नई सामग्री अपलोड करते हैं',
      'study_reminders': 'अध्ययन अनुस्मारक',
      'study_reminders_desc': 'दैनिक सीखने के अनुस्मारक',
      'promotions_offers': 'प्रचार और ऑफ़र',
      'promotions_offers_desc': 'छूट और विशेष ऑफ़र',
      // Chat
      'access_denied': 'पहुंच अस्वीकृत',
      'please_login_chat': 'सहायता से चैट करने के लिए कृपया लॉग इन करें।',
      'bharatam_support_chat': 'भारतम् सहायता चैट',
      'ask_anything_online': 'हमसे कुछ भी पूछें • ऑनलाइन',
      'start_conversation': 'बातचीत शुरू करें',
      'chat_intro_desc': 'हमसे पाठ्यक्रम विवरण, तकनीकी मुद्दों, भुगतान या प्रमाणपत्रों के बारे में पूछें। हमारी सहायता टीम आपका मार्गदर्शन करने के लिए तैयार है!',
      'support_admin': 'सहायता व्यवस्थापक',
      'type_message_hint': 'अपना संदेश लिखें...',
      // Search
      'search_placeholder': 'पाठ्यक्रम, प्रशिक्षक खोजें...',
      'type_to_search': 'खोज शुरू करने के लिए ऊपर लिखें...',
      'recent_searches': 'हाल की खोजें',
      'clear_all': 'सभी साफ़ करें',
      'no_courses_found': 'कोई पाठ्यक्रम नहीं मिला',
      'no_courses_found_desc': 'अपने खोज शब्दों को समायोजित करने या कोई अन्य फ़िल्टर लागू करने का प्रयास करें।',
      'filter_all': 'सभी',
      'filter_free': 'मुफ़्त',
      'filter_paid': 'सशुल्क',
      'filter_hindi': 'हिन्दी',
      'filter_english': 'अंग्रेज़ी',
      'filter_sanskrit': 'संस्कृत',
      // Course Detail
      'tab_videos': 'वीडियो',
      'tab_pdfs': 'पीडीएफ',
      'empty_videos': 'इस पाठ्यक्रम के लिए कोई वीडियो व्याख्यान उपलब्ध नहीं है।',
      'empty_pdfs': 'इस पाठ्यक्रम के लिए कोई पीडीएफ सामग्री उपलब्ध नहीं है।',
      'from_price': 'यहाँ से शुरू',
      'view_plans': 'योजनाएं देखें',
      'downloaded_success': '"{title}" सफलतापूर्वक डाउनलोड हो गया!',
      'videos_count_label': '{count} वीडियो',
      'modules_count_label': '{count} मॉड्यूल',
      // Video Player
      'rating_enabled': 'रेटिंग सक्षम',
      'complete_to_rate': 'रेट करने के लिए पूरा करें',
      'no_ratings_yet': 'अभी तक कोई रेटिंग नहीं',
      'your_rating_prefix': 'आपकी रेटिंग: {rating}',
      'give_rating': 'रेटिंग दें',
      'update_rating': 'रेटिंग अपडेट करें',
      'mark_complete': 'पूर्ण चिह्नित करें',
      'certificate': 'प्रमाणपत्र',
      'rate_this_lecture': 'इस व्याख्यान को रेट करें',
      'submit_rating': 'रेटिंग सबमिट करें',
      'rating_saved_msg': 'धन्यवाद। आपकी व्याख्यान रेटिंग सहेज ली गई है।',
      'initializing_player': 'प्लेयर प्रारंभ हो रहा है...',
      'loading_video': 'वीडियो लोड हो रहा है...',
      'pdf_learning_resource': 'पीडीएफ सीखने का संसाधन',
      'audio_only': 'केवल ऑडियो',
      // My Certificates
      'my_certificates': 'मेरे प्रमाणपत्र',
      'no_certs_earned_yet': 'अभी तक कोई प्रमाणपत्र अर्जित नहीं किया गया',
      'no_certs_earned_desc': 'अपने खरीदे गए किसी भी पाठ्यक्रम के व्याख्यानों को 100% पूरा करके अपना सत्यापित और डाउनलोड करने योग्य प्रमाणपत्र अनलॉक करें!',
      'verified_certificate': 'सत्यापित प्रमाणपत्र',
      'instructor_prefix': 'प्रशिक्षक: {name}',
      'earned_on': 'अर्जित तिथि',
      'view_download': 'देखें और डाउनलोड करें',
    },
    'mr': {
      'welcome_back': 'पुन्हा स्वागत आहे,',
      'find_course': 'तुम्हाला शिकायचा असलेला कोर्स शोधा',
      'categories': 'श्रेण्या',
      'featured_courses': 'वैशिष्ट्यीकृत अभ्यासक्रम',
      'search': 'शोधा',
      'home': 'एक्सप्लोर',
      'my_courses': 'अकादमी',
      'chat': 'चॅट',
      'feed': 'कम्युनिटी',
      'profile': 'अकाउंट',
      'edit_profile': 'प्रोफाइल संपादित करा',
      'language': 'भाषा (Language)',
      'notifications': 'अधिसूचना',
      'help_support': 'मदत आणि समर्थन',
      'about': 'आमच्याबद्दल',
      'logout': 'लॉग आउट',
      'courses': 'अभ्यासक्रम',
      'completed': 'पूर्ण केले',
      'certificates': 'प्रमाणपत्रे',
      'welcome_header': 'भारतम् लर्निंग प्लॅटफॉर्मवर आपले स्वागत आहे',
      'my_learning': 'माझे शिक्षण',
      'view_all': 'सर्व पहा',
      'top_instructors': 'उत्कृष्ट शिक्षक',
      'see_all': 'सर्व पहा',
      'no_courses_in': 'या श्रेणीत कोणतेही अभ्यासक्रम नाहीत:',
      'explore_other_category': 'कृपया दुसरी श्रेणी शोधा किंवा नंतर पुन्हा भेट द्या.',
      'progress_courses': 'प्रगतीपथावरील अभ्यासक्रम',
      'completed_courses': 'पूर्ण झालेले अभ्यासक्रम',
      'support_chat': 'मदत चॅट',
      'courses_suffix': 'अभ्यासक्रम',
      'no_completed_courses': 'पूर्ण झालेले अभ्यासक्रम नाहीत',
      'no_courses_in_progress': 'प्रगतीपथावरील अभ्यासक्रम नाहीत',
      'complete_lectures_to_earn': 'सत्यापित प्रमाणपत्र मिळविण्यासाठी अभ्यासक्रमातील सर्व व्याख्याने पूर्ण करा!',
      'explore_catalog_to_start': 'शिकणे सुरू करण्यासाठी आमचा कॅटलॉग एक्सप्लोर करा आणि अभ्यासक्रम खरेदी करा.',
      'view_certificate': 'प्रमाणपत्र पहा',
      'continue_learning': 'शिकणे सुरू ठेवा',
      'about_app_title': 'अॅपबद्दल',
      'about_app_desc': 'भारतम् एलएमएस ही एक प्रीमियम शिक्षण व्यवस्थापन प्रणाली आहे जी भारताचे शास्त्रीय ज्ञान जतन आणि सामायिक करण्यासाठी समर्पित आहे. वैदिक गणितापासून ते संस्कृत, योगापासून ते भारतीय इतिहासापर्यंत - संरचित अभ्यासक्रम, परस्परसंवादी मॉड्यूल आणि सत्यापित प्रमाणपत्रांसह तज्ञ प्रशिक्षकांकडून शिका.\n\nआधुनिक तंत्रज्ञानाच्या साहाय्याने जगभरातील विद्यार्थ्यांसाठी पारंपरिक भारतीय शिक्षण सुलभ करणे हे आमचे ध्येय आहे.',
      'how_to_use': 'कसे वापरावे',
      'browse_courses_step': 'अभ्यासक्रम ब्राउझ करा',
      'browse_courses_desc': 'होम स्क्रीनवर आमच्या अभ्यासक्रमांची यादी शोधा',
      'purchase_content_step': 'सामग्री खरेदी करा',
      'purchase_content_desc': 'पूर्ण अभ्यासक्रम, वैयक्तिक मॉड्युल्स किंवा एकल व्हिडिओ खरेदी करा',
      'watch_learn_step': 'पहा आणि शिका',
      'watch_learn_desc': 'कधीही व्हिडिओ स्ट्रीम करा, आपल्या प्रगतीचा मागोवा घ्या',
      'earn_certificate_step': 'प्रमाणपत्र मिळवा',
      'earn_certificate_desc': 'सत्यापित प्रमाणपत्र मिळविण्यासाठी सर्व व्हिडिओ पूर्ण करा',
      'key_features': 'मुख्य वैशिष्ट्ये',
      'hd_video': 'एचडी व्हिडिओ स्ट्रीमिंग',
      'verified_certs': 'सत्यापित प्रमाणपत्रे',
      'multi_lang': 'बहुभाषिक समर्थन',
      'secure_content': 'सुरक्षित सामग्री संरक्षण',
      'dark_mode': 'डार्क मोड',
      'made_with_love': 'भारतात ❤️ सह तयार केले',
      'copyright': '© 2026 भारतम् एलएमएस. सर्व हक्क राखीव.',
      'how_can_we_help': 'आम्ही तुम्हाला कशी मदत करू शकतो?',
      'here_to_assist': 'आम्ही तुम्हाला कोणत्याही गोष्टीसाठी मदत करण्यास येथे आहोत',
      'faqs': 'नेहमी विचारले जाणारे प्रश्न',
      'contact_us': 'आमच्याशी संपर्क साधा',
      'email_support': 'ईमेल सपोर्ट',
      'call_us': 'आम्हाला कॉल करा',
      'whatsapp': 'व्हॉट्सअॅप',
      'faq_q1': 'मी अभ्यासक्रम कसा खरेदी करू?',
      'faq_a1': 'अभ्यासक्रम तपशील पृष्ठावर जा आणि किंमत बटणावर टॅप करा. तुम्ही संपूर्ण अभ्यासक्रम, वैयक्तिक मॉड्युल्स किंवा एकल व्हिडिओ खरेदी करू शकता.',
      'faq_q2': 'मला परतावा मिळू शकतो का?',
      'faq_a2': 'होय! आम्ही सर्व खरेदीसाठी 30 दिवसांचे परतावा धोरण ऑफर करतो. परतावा सुरू करण्यासाठी सपोर्टशी संपर्क साधा.',
      'faq_q3': 'मी माझे प्रमाणपत्र कसे डाउनलोड करू?',
      'faq_a3': 'एकदा तुम्ही अभ्यासक्रमातील सर्व व्हिडिओ पूर्ण केले की, माझे अभ्यासक्रम → पूर्ण → प्रमाणपत्र पहा → डाउनलोड करा वर जा.',
      'faq_q4': 'मी अॅपची भाषा कशी बदलू?',
      'faq_a4': 'प्रोफाइल → भाषा वर जा आणि आपली पसंतीची भाषा (इंग्रजी, हिंदी किंवा मराठी) निवडा.',
      'logout_confirm_title': 'लॉग आउट करायचे?',
      'logout_confirm_msg': 'तुम्हाला खात्री आहे की तुम्ही लॉग आउट करू इच्छिता? तुमच्या अभ्यासक्रमांमध्ये प्रवेश मिळवण्यासाठी तुम्हाला पुन्हा लॉग इन करावे लागेल.',
      'cancel': 'रद्द करा',
      // Edit Profile
      'full_name': 'पूर्ण नाव',
      'phone_number': 'फोन नंबर',
      'email_optional': 'ईमेल (पर्यायी)',
      'save_changes': 'बदल जतन करा',
      'profile_updated': 'प्रोफाइल यशस्वीरित्या अपडेट केली!',
      // Notifications
      'stay_updated': 'अपडेट राहा',
      'manage_notif_pref': 'तुमच्या अधिसूचना प्राधान्ये व्यवस्थापित करा',
      'push_notifications': 'पुश अधिसूचना',
      'course_updates': 'अभ्यासक्रम अपडेट',
      'get_notif_enrolled_courses': 'नोंदणी केलेल्या अभ्यासक्रमांबद्दल माहिती मिळवा',
      'new_videos': 'नवीन व्हिडिओ',
      'new_videos_desc': 'जेव्हा शिक्षक नवीन सामग्री अपलोड करतात',
      'study_reminders': 'अभ्यासाचे स्मरणपत्र',
      'study_reminders_desc': 'दैनिक अभ्यासाचे स्मरणपत्र',
      'promotions_offers': 'जाहिराती आणि ऑफर्स',
      'promotions_offers_desc': 'सवलत आणि विशेष ऑफर्स',
      // Chat
      'access_denied': 'प्रवेश नाकारला',
      'please_login_chat': 'मदत चॅट सुरू करण्यासाठी कृपया लॉग इन करा.',
      'bharatam_support_chat': 'भारतम् मदत चॅट',
      'ask_anything_online': 'आम्हाला काहीही विचारा • ऑनलाइन',
      'start_conversation': 'संभाषण सुरू करा',
      'chat_intro_desc': 'आम्हाला अभ्यासक्रम तपशील, तांत्रिक समस्या, पेमेंट किंवा प्रमाणपत्रांबद्दल विचारा. आमची सपोर्ट टीम तुम्हाला मदत करण्यासाठी तयार आहे!',
      'support_admin': 'मदत प्रशासक',
      'type_message_hint': 'तुमचा संदेश टाइप करा...',
      // Search
      'search_placeholder': 'अभ्यासक्रम, शिक्षक शोधा...',
      'type_to_search': 'शोध सुरू करण्यासाठी वर टाइप करा...',
      'recent_searches': 'अलीकडील शोध',
      'clear_all': 'सर्व साफ करा',
      'no_courses_found': 'कोणतेही अभ्यासक्रम आढळले नाहीत',
      'no_courses_found_desc': 'तुमचे शोध शब्द बदलण्याचा किंवा दुसरा फिल्टर वापरण्याचा प्रयत्न करा.',
      'filter_all': 'सर्व',
      'filter_free': 'मोफत',
      'filter_paid': 'पेड',
      'filter_hindi': 'हिंदी',
      'filter_english': 'इंग्रजी',
      'filter_sanskrit': 'संस्कृत',
      // Course Detail
      'tab_videos': 'व्हिडिओ',
      'tab_pdfs': 'पीडीएफ',
      'empty_videos': 'या अभ्यासक्रमासाठी कोणतेही व्हिडिओ व्याख्यान उपलब्ध नाही.',
      'empty_pdfs': 'या अभ्यासक्रमासाठी कोणतेही पीडीएफ साहित्य उपलब्ध नाही.',
      'from_price': 'येथून सुरू',
      'view_plans': 'प्लॅन्स पहा',
      'downloaded_success': '"{title}" यशस्वीरित्या डाउनलोड झाले!',
      'videos_count_label': '{count} व्हिडिओ',
      'modules_count_label': '{count} मॉड्युल्स',
      // Video Player
      'rating_enabled': 'रेटिंग सुरू केले',
      'complete_to_rate': 'रेटिंग देण्यासाठी पूर्ण करा',
      'no_ratings_yet': 'अद्याप रेटिंग नाही',
      'your_rating_prefix': 'तुमचे रेटिंग: {rating}',
      'give_rating': 'रेटिंग द्या',
      'update_rating': 'रेटिंग अपडेट करा',
      'mark_complete': 'पूर्ण म्हणून चिन्हांकित करा',
      'certificate': 'प्रमाणपत्र',
      'rate_this_lecture': 'या व्याख्यानाला रेटिंग द्या',
      'submit_rating': 'रेटिंग सबमिट करा',
      'rating_saved_msg': 'धन्यवाद. तुमची व्याख्यान रेटिंग जतन केली गेली आहे.',
      'initializing_player': 'प्लेअर सुरू होत आहे...',
      'loading_video': 'व्हिडिओ लोड होत आहे...',
      'pdf_learning_resource': 'पीडीएफ अभ्यास साहित्य',
      'audio_only': 'फक्त ऑडिओ',
      // My Certificates
      'my_certificates': 'माझी प्रमाणपत्रे',
      'no_certs_earned_yet': 'अद्याप एकही प्रमाणपत्र मिळवलेले नाही',
      'no_certs_earned_desc': 'तुमच्या खरेदी केलेल्या कोणत्याही अभ्यासक्रमातील सर्व व्याख्याने १००% पूर्ण करा आणि तुमचे सत्यापित, डाउनलोड करण्यायोग्य प्रमाणपत्र मिळवा!',
      'verified_certificate': 'सत्यापित प्रमाणपत्र',
      'instructor_prefix': 'प्रशिक्षक: {name}',
      'earned_on': 'मिळवलेली तारीख',
      'view_download': 'पहा आणि डाउनलोड करा',
    },
  };

  static String get(String key) {
    final lang = localeNotifier.value;
    return _translations[lang]?[key] ?? _translations['en']?[key] ?? key;
  }

  static String getWithArgs(String key, Map<String, String> args) {
    String val = get(key);
    args.forEach((k, v) {
      val = val.replaceAll('{$k}', v);
    });
    return val;
  }
}